# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registraion',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
