# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-22 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0006_auto_20170221_1229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Worktime',
            new_name='Journal',
        ),
    ]
